name: Daily Parser

on:
  push:
#  schedule:
#    - cron: '0 9 * * *'

jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Parsers
        run: python gohome.py domovita.py flatbook.py hata.py neagent.py
      - name: Analyse Data
        run: python analysis_of_csv.py analysis_of_parsed.py