name: Daily Parser

on:
  schedule:
    - cron: '0 21 * * *'

env:
  ACTION_GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}

jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Parsers
        run: python gohome.py
      - name: Run Parsers
        run: python domovita.py
      - name: Run Parsers
        run: python flatbook.py
      - name: Run Parsers
        run: python hata.py
      - name: Run Parsers
        run: python neagent.py
      - name: Analyse Data
        run: python analysis_of_parsed.py
      - name: Set Git User (Global)
        run: |
            git config --global user.email "kupratsevchlyosha19@gmail.com"
            git config --global user.name "MCBORAU"
      - name: Prepare updated files
        run: |
            git add .
      - name: Create commit message
        run: |
            git commit -m "Autocommit"
      - name: Push changes to remoted repo
        run: git push origin main